version: "3.1"

services:
  db:
      image: postgres:13.0-alpine
      restart: always
      ports:
        - "5433:5432"
      volumes:
        - "./db:/var/lib/postgresql/data"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty123
        POSTGRES_DB: tasker

  app:
      build: .
      restart: always
      ports:
        - "8081:8000"
      volumes:
        - "./app:/app"
      command: "/app/start.sh"
